local_costmap:
    footprint: [[0.325,0.225],[0.325,-0.225],[-0.325,-0.225],[-0.325,0.225]] #ËÄ±ßÐÎ³µË³ÊÆÕëÄæÊ±Õë×ø±ê¶¼¿ÉÒÔ
    footprint_padding: 0.01
    transform_tolerance: 1.0
    update_frequency: 3.0
    publish_frequency: 1.0

    global_frame: map
    robot_base_frame: base_link
    resolution: 0.05
    static_map: false
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05

    plugins:            
        - {name: sensor,    type: "costmap_2d::ObstacleLayer"}
        - {name: inflation, type: "costmap_2d::InflationLayer"}

    sensor:
        observation_sources: laser_scan_sensor
        laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

    inflation:
        inflation_radius: 0.23
        cost_scaling_factor: 8.0
